export const AUDIT_ACTIONS = {
  STATUS_CHANGE: "STATUS_CHANGE",
  MEMBER_INVITE: "MEMBER_INVITE",
  MEMBER_ROLE_CHANGE: "MEMBER_ROLE_CHANGE",
  MEMBER_REMOVE: "MEMBER_REMOVE",
  PROJECT_ARCHIVE: "PROJECT_ARCHIVE",
  OWNERSHIP_TRANSFER: "OWNERSHIP_TRANSFER",
  PAYMENT_CREATE: "PAYMENT_CREATE",
  PAYMENT_EDIT: "PAYMENT_EDIT",
  PAYMENT_DELETE: "PAYMENT_DELETE",
  SALE_STATUS_CHANGE: "SALE_STATUS_CHANGE",
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_UPDATE: "PROJECT_UPDATE",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
