export const PROJECT_ROLES = [
  "OWNER_ADMIN",
  "PROJECT_MANAGER",
  "INVENTORY_MANAGER",
  "SITE_MANAGER",
  "VIEWER",
] as const;

export type ProjectRole = (typeof PROJECT_ROLES)[number];

export const CAPABILITIES = [
  "project.read",
  "estate.read",
  "land.read",
  "unit.read",
  "development.read",
  "sale.read",
  "payment.read",
  "document.read",
  "audit.read",
  "report.read",
  "project.update",
  "project.archive",
  "member.invite",
  "member.roleChange",
  "member.remove",
  "ownership.transfer",
  "estate.write",
  "land.write",
  "building.write",
  "unit.write",
  "development.write",
  "development.proposeComplete",
  "development.approveComplete",
  "phase.write",
  "milestone.write",
  "progress.write",
  "spend.write",
  "contractor.write",
  "buyer.write",
  "sale.write",
  "sale.reopenSold",
  "payment.create",
  "payment.editOwn24h",
  "payment.editAny",
  "payment.delete",
  "document.write",
] as const;

export type Capability = (typeof CAPABILITIES)[number];

const Y = true;
const N = false;

/** Spec §4.6 — role × capability. Scoped roles still require MembershipScope checks. */
export const PERMISSION_MATRIX: Record<ProjectRole, Record<Capability, boolean>> = {
  OWNER_ADMIN: Object.fromEntries(CAPABILITIES.map((c) => [c, Y])) as Record<Capability, boolean>,
  PROJECT_MANAGER: {
    "project.read": Y,
    "estate.read": Y,
    "land.read": Y,
    "unit.read": Y,
    "development.read": Y,
    "sale.read": Y,
    "payment.read": Y,
    "document.read": Y,
    "audit.read": Y,
    "report.read": Y,
    "project.update": Y,
    "project.archive": N,
    "member.invite": N,
    "member.roleChange": N,
    "member.remove": N,
    "ownership.transfer": N,
    "estate.write": Y,
    "land.write": Y,
    "building.write": Y,
    "unit.write": Y,
    "development.write": Y,
    "development.proposeComplete": Y,
    "development.approveComplete": N,
    "phase.write": Y,
    "milestone.write": Y,
    "progress.write": Y,
    "spend.write": Y,
    "contractor.write": Y,
    "buyer.write": Y,
    "sale.write": Y,
    "sale.reopenSold": N,
    "payment.create": Y,
    "payment.editOwn24h": Y,
    "payment.editAny": N,
    "payment.delete": N,
    "document.write": Y,
  },
  INVENTORY_MANAGER: {
    "project.read": Y,
    "estate.read": Y,
    "land.read": Y,
    "unit.read": Y,
    "development.read": Y,
    "sale.read": Y,
    "payment.read": Y,
    "document.read": Y,
    "audit.read": Y,
    "report.read": Y,
    "project.update": N,
    "project.archive": N,
    "member.invite": N,
    "member.roleChange": N,
    "member.remove": N,
    "ownership.transfer": N,
    "estate.write": Y,
    "land.write": Y,
    "building.write": Y,
    "unit.write": Y,
    "development.write": N,
    "development.proposeComplete": N,
    "development.approveComplete": N,
    "phase.write": N,
    "milestone.write": N,
    "progress.write": N,
    "spend.write": N,
    "contractor.write": N,
    "buyer.write": Y,
    "sale.write": Y,
    "sale.reopenSold": N,
    "payment.create": Y,
    "payment.editOwn24h": Y,
    "payment.editAny": N,
    "payment.delete": N,
    "document.write": Y,
  },
  SITE_MANAGER: {
    "project.read": Y,
    "estate.read": Y,
    "land.read": Y,
    "unit.read": Y,
    "development.read": Y,
    "sale.read": Y,
    "payment.read": Y,
    "document.read": Y,
    "audit.read": Y,
    "report.read": Y,
    "project.update": N,
    "project.archive": N,
    "member.invite": N,
    "member.roleChange": N,
    "member.remove": N,
    "ownership.transfer": N,
    "estate.write": Y,
    "land.write": Y,
    "building.write": Y,
    "unit.write": Y,
    "development.write": Y,
    "development.proposeComplete": Y,
    "development.approveComplete": N,
    "phase.write": Y,
    "milestone.write": Y,
    "progress.write": Y,
    "spend.write": Y,
    "contractor.write": N,
    "buyer.write": N,
    "sale.write": N,
    "sale.reopenSold": N,
    "payment.create": N,
    "payment.editOwn24h": N,
    "payment.editAny": N,
    "payment.delete": N,
    "document.write": Y,
  },
  VIEWER: {
    "project.read": Y,
    "estate.read": Y,
    "land.read": Y,
    "unit.read": Y,
    "development.read": Y,
    "sale.read": Y,
    "payment.read": Y,
    "document.read": Y,
    "audit.read": Y,
    "report.read": Y,
    "project.update": N,
    "project.archive": N,
    "member.invite": N,
    "member.roleChange": N,
    "member.remove": N,
    "ownership.transfer": N,
    "estate.write": N,
    "land.write": N,
    "building.write": N,
    "unit.write": N,
    "development.write": N,
    "development.proposeComplete": N,
    "development.approveComplete": N,
    "phase.write": N,
    "milestone.write": N,
    "progress.write": N,
    "spend.write": N,
    "contractor.write": N,
    "buyer.write": N,
    "sale.write": N,
    "sale.reopenSold": N,
    "payment.create": N,
    "payment.editOwn24h": N,
    "payment.editAny": N,
    "payment.delete": N,
    "document.write": N,
  },
};

export const SCOPED_ROLES: ProjectRole[] = ["SITE_MANAGER", "VIEWER"];

export function roleAllows(role: ProjectRole, capability: Capability) {
  return PERMISSION_MATRIX[role][capability];
}

export function enumeratePermissionCases() {
  const cases: Array<{ role: ProjectRole; capability: Capability; allowed: boolean }> = [];
  for (const role of PROJECT_ROLES) {
    for (const capability of CAPABILITIES) {
      cases.push({
        role,
        capability,
        allowed: PERMISSION_MATRIX[role][capability],
      });
    }
  }
  return cases;
}
